export type EmploymentStatusKey =
  | "unemployed_active"
  | "employed_open"
  | "career_transition"
  | "student"
  | "high_school_student"
  | "first_job"
  | "freelance";

export const EMPLOYMENT_STATUS_CONFIG: Record<
  EmploymentStatusKey,
  { label: string; icon: string; description: string; badgeColor: string }
> = {
  unemployed_active: {
    label: "Buscando Recolocação",
    icon: "🎯",
    description: "Desempregado(a) em busca ativa por novos desafios",
    badgeColor: "bg-blue-500/10 text-blue-600 dark:text-blue-400 border-blue-500/20",
  },
  employed_open: {
    label: "Aberto(a) a Propostas",
    icon: "💼",
    description: "Empregado(a), mas atento(a) a oportunidades melhores",
    badgeColor: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400 border-emerald-500/20",
  },
  career_transition: {
    label: "Transição de Carreira",
    icon: "🔄",
    description: "Mudando de área ou pivotando competências",
    badgeColor: "bg-purple-500/10 text-purple-600 dark:text-purple-400 border-purple-500/20",
  },
  student: {
    label: "Estudante Universitário / Técnico",
    icon: "📚",
    description: "Cursando ensino superior ou técnico e se preparando para o mercado",
    badgeColor: "bg-cyan-500/10 text-cyan-600 dark:text-cyan-400 border-cyan-500/20",
  },
  high_school_student: {
    label: "Estudante do Ensino Médio",
    icon: "🎒",
    description: "Cursando o ensino médio, focado em ENEM, vestibulares ou Jovem Aprendiz",
    badgeColor: "bg-teal-500/10 text-teal-600 dark:text-teal-400 border-teal-500/20",
  },
  first_job: {
    label: "Primeiro Emprego / Estágio",
    icon: "🎓",
    description: "Iniciando a jornada profissional ou acadêmica",
    badgeColor: "bg-amber-500/10 text-amber-600 dark:text-amber-400 border-amber-500/20",
  },
  freelance: {
    label: "Autônomo / Freelancer",
    icon: "🚀",
    description: "Prestando serviços de forma independente",
    badgeColor: "bg-pink-500/10 text-pink-600 dark:text-pink-400 border-pink-500/20",
  },
};

export interface DailyMotivation {
  id: number;
  quote: string;
  author: string;
  tip: string;
  memeTitle: string;
  memeSetup: string;
  memePunchline: string;
  memeTag: string;
}

export interface DailyMotivationProfile {
  careerSegment?: string | null;
  area?: string | null;
  currentArea?: string | null;
  studyCourse?: string | null;
}

const MOTIVATION_CATALOG: Record<EmploymentStatusKey, DailyMotivation[]> = {
  unemployed_active: [
    {
      id: 1,
      quote: "O não você já tem. O sim está no próximo currículo ajustado estrategicamente.",
      author: "Sabedoria de Carreira",
      tip: "Hoje, personalize 2 candidaturas focando nas competências chave exigidas na descrição da vaga.",
      memeTitle: "A saga do processo seletivo",
      memeSetup: "Entrevistador: 'Procuramos um profissional dinâmico, multitarefa e resiliente.'",
      memePunchline: "Candidato: 'Perfeito! Consigo responder e-mails, tomar café e manter a calma enquanto espero o retorno há 3 semanas.' 😂",
      memeTag: "Expectativa vs Realidade",
    },
    {
      id: 2,
      quote: "A persistência é o caminho do êxito. Cada entrevista é um aprendizado rumo à oportunidade certa.",
      author: "Charles Chaplin",
      tip: "Atualize seu resumo profissional e envie 1 mensagem amigável para uma conexão do seu setor.",
      memeTitle: "Notificação do celular",
      memeSetup: "Celular toca: 🔔 'Você recebeu uma nova mensagem!'",
      memePunchline: "Esperança: 'É o RH me chamando pra entrevista!' | Realidade: 'Sua fatura do cartão foi gerada.' 🥲",
      memeTag: "Vida de Candidato",
    },
    {
      id: 3,
      quote: "Não pare até se orgulhar do resultado dos seus esforços.",
      author: "Foco & Determinação",
      tip: "Revise a formatação do seu currículo para garantir leitura clara em qualquer dispositivo.",
      memeTitle: "Formulário da Vaga vs Currículo",
      memeSetup: "Site de Vagas: 'Por favor, anexe seu currículo em PDF.'",
      memePunchline: "Logo em seguida: 'Agora preencha manualmente cada uma das últimas 10 experiências desde a infância.' 🤡",
      memeTag: "Rotina de Inscrição",
    },
    {
      id: 4,
      quote: "Buscar emprego é um trabalho em si mesmo. Trate como tal: com rotina, meta e descanso.",
      author: "Disciplina de Busca",
      tip: "Defina um horário fixo hoje só para candidaturas — e um horário fixo para desligar e descansar.",
      memeTitle: "Rotina do candidato dedicado",
      memeSetup: "Eu às 8h: 'Hoje vou candidatar-me a 5 vagas com calma e método.'",
      memePunchline: "Eu às 23h: 47 abas abertas e ainda perguntando 'só mais uma vaguinha?' 🌙💻",
      memeTag: "Expectativa vs Realidade",
    },
    {
      id: 5,
      quote: "Rejeição em processo seletivo não é sobre seu valor, é sobre encaixe de momento. Encaixe muda.",
      author: "Perspectiva de Carreira",
      tip: "Peça feedback educadamente para o último processo que não avançou — nem sempre respondem, mas vale tentar.",
      memeTitle: "E-mail de feedback automático",
      memeSetup: "E-mail da empresa: 'Agradecemos seu interesse, seguiremos com outros candidatos.'",
      memePunchline: "Eu, decodificando: 'Traduzindo: eles têm um candidato interno e me usaram pra cumprir tabela.' 🕵️📧",
      memeTag: "Vida de Candidato",
    },
    {
      id: 6,
      quote: "Cada candidatura enviada é uma semente. Nem toda semente vira planta, mas sem plantar não cresce nada.",
      author: "Paciência Estratégica",
      tip: "Organize suas candidaturas em uma planilha simples: empresa, vaga, data e status — clareza reduz ansiedade.",
      memeTitle: "Planilha de controle de vagas",
      memeSetup: "Eu criando a planilha: 'Agora vou ter controle total do processo!'",
      memePunchline: "Eu 3 semanas depois: 42 linhas, coluna 'status' toda escrito 'aguardando' e uma fé inabalável. 📊🙏",
      memeTag: "Rotina de Inscrição",
    },
    {
      id: 7,
      quote: "Você não está atrasado(a). Cada carreira tem seu próprio relógio, e o seu ainda está no horário certo.",
      author: "Ritmo Próprio",
      tip: "Pare de comparar seu tempo de busca com o de outras pessoas hoje. Compare só com sua última semana.",
      memeTitle: "Comparação nas redes sociais",
      memeSetup: "Feed: 'Fulano conseguiu a vaga dos sonhos em 2 semanas!'",
      memePunchline: "Eu, na semana 8 de busca: fechando o app e lembrando que ninguém posta a fila de rejeições. 📱🙄",
      memeTag: "Vida de Candidato",
    },
    {
      id: 8,
      quote: "O currículo abre a porta. A entrevista é sua, e nela você mostra o que nenhum papel consegue dizer.",
      author: "Preparação Consciente",
      tip: "Prepare 2 perguntas inteligentes para fazer ao entrevistador — isso também é parte da sua avaliação.",
      memeTitle: "Pergunta final da entrevista",
      memeSetup: "Entrevistador: 'Você tem alguma pergunta para mim?'",
      memePunchline: "Eu, que preparei tudo menos isso: 'Hã... vocês têm café na copa?' ☕😅",
      memeTag: "Expectativa vs Realidade",
    },
    {
      id: 9,
      quote: "Buscar emprego cansa porque exige esperança repetida. Isso não é fraqueza, é coragem em loop.",
      author: "Resiliência Real",
      tip: "Se hoje o cansaço bateu, tudo bem pausar 1 dia. Retomar amanhã também é estratégia.",
      memeTitle: "Motivação em queda livre",
      memeSetup: "Eu de manhã: 'Hoje vou mandar 10 currículos, sem desculpa.'",
      memePunchline: "Eu às 15h: 1 currículo enviado, 3 séries assistidas e uma soneca 'estratégica'. 😴📺",
      memeTag: "Vida de Candidato",
    },
    {
      id: 10,
      quote: "Toda recolocação começa com alguém disposto a te dar uma chance. Aumente as chances de encontrar essa pessoa.",
      author: "Estratégia de Visibilidade",
      tip: "Ative o aviso de 'aberto a oportunidades' no LinkedIn — recrutadores procuram isso ativamente.",
      memeTitle: "Configuração 'open to work'",
      memeSetup: "Eu ativando o badge verde no LinkedIn: 'Agora sim, chuva de propostas.'",
      memePunchline: "Minha caixa de mensagens: 1 convite de curso de MLM e um pedido de conexão de robô. 🤖📩",
      memeTag: "Rotina de Inscrição",
    },
    {
      id: 11,
      quote: "Adaptar o currículo pra cada vaga não é enrolação, é a diferença entre ser visto e ser ignorado pelo ATS.",
      author: "Estratégia Prática",
      tip: "Copie 3 palavras-chave literais da descrição da vaga para dentro do seu currículo, nas seções certas.",
      memeTitle: "Sistema ATS filtrando currículos",
      memeSetup: "Sistema: 'Buscando pelas palavras-chave exatas da vaga...'",
      memePunchline: "Meu currículo genérico enviado pra 30 vagas diferentes: 'Ué, por que ninguém me chama?' 🤖📄",
      memeTag: "Rotina de Inscrição",
    },
    {
      id: 12,
      quote: "Silêncio do recrutador não é resposta. Enquanto não vier o 'não', o processo ainda está em aberto.",
      author: "Paciência Ativa",
      tip: "Se já se passaram 7 dias úteis do prazo prometido, mande uma mensagem educada perguntando a posição do processo.",
      memeTitle: "Prazo prometido pelo RH",
      memeSetup: "RH: 'Te retornamos até sexta-feira com uma posição.'",
      memePunchline: "Sexta-feira, sábado, domingo, a próxima sexta-feira: eu ainda checando e-mail a cada 10 minutos. 📆👀",
      memeTag: "Vida de Candidato",
    },
  ],
  employed_open: [
    {
      id: 1,
      quote: "A melhor hora para procurar uma nova oportunidade é enquanto você já está produzindo e ativo.",
      author: "Estratégia Profissional",
      tip: "Mantenha seus contatos profissionais aquecidos e seu perfil atualizado com suas conquistas recentes.",
      memeTitle: "Reunião que poderia ser e-mail",
      memeSetup: "Chefe: 'Vamos fazer uma reunião rápida de alinhamento de 5 minutos.'",
      memePunchline: "2 horas depois: Discutindo a cor do clipe de papel enquanto penso na minha carreira. ☕🫣",
      memeTag: "Cotidiano de Trabalho",
    },
    {
      id: 2,
      quote: "Seu valor não diminui pela incapacidade de alguém de enxergar o seu potencial no trabalho atual.",
      author: "Foco no Crescimento",
      tip: "Mapeie 3 empresas referências na sua área e acompanhe as vagas que elas abrem frequentemente.",
      memeTitle: "Roupa da Entrevista Secreta",
      memeSetup: "Colega de trabalho: 'Nossa, por que você veio tão arrumado(a) hoje?'",
      memePunchline: "Eu: 'Ah, sabe como é... resolvi dar um upgrade no meu visual na terça-feira!' 🤫💼",
      memeTag: "Modo Furtivo",
    },
    {
      id: 3,
      quote: "Trocar de emprego não é traição com quem te contratou, é lealdade com quem você quer ser.",
      author: "Estratégia Profissional",
      tip: "Peça feedback 360° discretamente com colegas de confiança para saber onde você já está pronto(a) para o próximo passo.",
      memeTitle: "Entrevista no horário de almoço",
      memeSetup: "Eu: 'Só vou dar uma esticada no almoço hoje, com licença.'",
      memePunchline: "70 minutos depois, de terno debaixo do casaco: 'Trânsito, viu...' 🕐🧥",
      memeTag: "Operação Sigilo",
    },
    {
      id: 4,
      quote: "Estar bem empregado não é motivo pra parar de evoluir, é o momento ideal pra escolher com calma.",
      author: "Estratégia Profissional",
      tip: "Liste 2 habilidades que te fariam candidato(a) ideal para o próximo passo e comece a desenvolvê-las hoje.",
      memeTitle: "LinkedIn no modo discreto",
      memeSetup: "Eu navegando vagas no LinkedIn: 'Só curiosidade, não é nada sério.'",
      memePunchline: "Também eu, 10 minutos depois, já calculando quanto tempo de trajeto teria pro escritório novo. 🗺️👀",
      memeTag: "Modo Furtivo",
    },
    {
      id: 5,
      quote: "Você pode gostar do seu trabalho e ainda assim querer mais. As duas coisas cabem juntas.",
      author: "Foco no Crescimento",
      tip: "Anote 1 conquista concreta deste mês (número, resultado, elogio) para usar em futuras negociações.",
      memeTitle: "Feedback positivo do chefe",
      memeSetup: "Chefe: 'Você tem entregado muito bem, parabéns!'",
      memePunchline: "Eu, sorrindo por fora, calculando reajuste de mercado por dentro. 😊🧮",
      memeTag: "Cotidiano de Trabalho",
    },
    {
      id: 6,
      quote: "Networking não é pedir favor, é manter portas abertas para quando você precisar — ou quando alguém precisar de você.",
      author: "Estratégia Profissional",
      tip: "Comente ou reaja em uma publicação de alguém da sua rede profissional hoje, sem pedir nada em troca.",
      memeTitle: "Curtida estratégica no LinkedIn",
      memeSetup: "Eu curtindo o post do ex-colega: 'Só sendo gentil, nada demais.'",
      memePunchline: "Eu também, guardando mentalmente: 'Ele trabalha numa empresa boa, hein...' 👀💼",
      memeTag: "Rede de Contatos",
    },
    {
      id: 7,
      quote: "Estar empregado não significa estar acomodado(a). Dá pra cuidar bem do presente e namorar o futuro ao mesmo tempo.",
      author: "Dupla Atenção",
      tip: "Salve 1 vaga interessante hoje, mesmo sem intenção de se candidatar agora — é bom saber o que existe no mercado.",
      memeTitle: "Vaga salva 'só para ver depois'",
      memeSetup: "Eu salvando a vaga: 'É só pra ter noção de mercado, não vou nem me candidatar.'",
      memePunchline: "Eu, 3 dias depois, já com a carta de apresentação pronta. 📌😏",
      memeTag: "Modo Furtivo",
    },
    {
      id: 8,
      quote: "Pedir aumento não é ingratidão, é reconhecer seu próprio valor antes que alguém precise te lembrar disso.",
      author: "Autovalorização Profissional",
      tip: "Monte um documento simples com 3 resultados mensuráveis que você entregou nos últimos 6 meses.",
      memeTitle: "Reunião de pedido de aumento",
      memeSetup: "Eu entrando na sala: 'Vim discutir minha remuneração com dados concretos e profissionalismo.'",
      memePunchline: "Eu 2 minutos depois: rindo nervoso(a) e falando de futebol antes de tocar no assunto. 😅⚽",
      memeTag: "Cotidiano de Trabalho",
    },
    {
      id: 9,
      quote: "Um emprego bom de verdade é aquele que você escolheria de novo, sabendo o que sabe hoje.",
      author: "Clareza de Escolha",
      tip: "Faça uma lista rápida: o que te faria ficar mais 2 anos aqui, e o que te faria sair amanhã.",
      memeTitle: "Teste do café da manhã",
      memeSetup: "Pergunta clássica: 'Você acordaria feliz pra trabalhar aqui pelos próximos 5 anos?'",
      memePunchline: "Eu, tomando café e encarando a resposta sincera pela primeira vez em meses. ☕🤔",
      memeTag: "Cotidiano de Trabalho",
    },
    {
      id: 10,
      quote: "Manter o currículo atualizado enquanto está empregado(a) é seguro, não deslealdade.",
      author: "Preparação Contínua",
      tip: "Atualize hoje uma única seção do seu currículo — a de conquistas recentes já resolve muito.",
      memeTitle: "Currículo desatualizado há anos",
      memeSetup: "Eu abrindo meu currículo pra atualizar: 'Ainda diz que sou estagiário(a) de 2019...'",
      memePunchline: "10 promoções depois, meu currículo continua no mesmo cargo do início. 📄🦕",
      memeTag: "Modo Furtivo",
    },
    {
      id: 11,
      quote: "O melhor momento pra negociar é quando você não precisa desesperadamente da vaga nova. Empregado(a), você negocia melhor.",
      author: "Poder de Negociação",
      tip: "Se receber uma proposta nova, compare benefícios totais, não só o salário — plano de saúde e VR pesam na conta.",
      memeTitle: "Proposta de vaga concorrente",
      memeSetup: "Recrutador da vaga nova: 'Temos uma proposta salarial bem interessante para você.'",
      memePunchline: "Eu, calculando mentalmente: 'Interessante quanto, exatamente? Fala com números, por favor.' 🧮😌",
      memeTag: "Operação Sigilo",
    },
    {
      id: 12,
      quote: "Sentir-se estagnado(a) no cargo atual é sinal, não sentença. Sinais servem para você agir, não para se conformar.",
      author: "Escuta Interna",
      tip: "Identifique se o problema é a empresa, o cargo ou a rotina — a solução muda dependendo da resposta.",
      memeTitle: "Domingo à noite antes da segunda",
      memeSetup: "Meu corpo às 20h de domingo: ansiedade automática antecipando a semana.",
      memePunchline: "Eu: 'Será que é a empresa ou sou eu que preciso de férias?' Provavelmente as duas coisas. 😩📅",
      memeTag: "Cotidiano de Trabalho",
    },
  ],
  career_transition: [
    {
      id: 1,
      quote: "Nunca é tarde demais para ser aquilo que você poderia ter sido.",
      author: "George Eliot",
      tip: "Destaque suas competências comportamentais e bagagem prática que enriquecem o novo setor.",
      memeTitle: "Mudando de Área",
      memeSetup: "Eu ontem: 'Domino tudo da minha área antiga com o pé nas costas!'",
      memePunchline: "Eu hoje aprendendo os novos termos: 'Achei que sabia português até ver os jargões desse setor!' 🧠💥",
      memeTag: "Nível Aprendiz",
    },
    {
      id: 2,
      quote: "Coragem é a decisão de que o seu crescimento é mais importante que o receio do novo.",
      author: "Desenvolvimento de Carreira",
      tip: "Conecte-se com pessoas que já trabalham na sua área de destino para pegar dicas reais.",
      memeTitle: "Transição Sem Filtro",
      memeSetup: "Amigos: 'Que incrível sua coragem de mudar de profissão!'",
      memePunchline: "Eu estudando a nova área de madrugada com 3 xícaras de café: 'Corajoso(a) ou louco(a)?' ☕😵‍💫",
      memeTag: "Vida Real",
    },
    {
      id: 3,
      quote: "Sua experiência anterior não foi tempo perdido, foi o alicerce que ninguém mais tem na área nova.",
      author: "Reposicionamento de Carreira",
      tip: "Escreva 3 conquistas da sua área antiga traduzidas para o vocabulário da área nova — isso vira ouro na entrevista.",
      memeTitle: "Currículo em dois mundos",
      memeSetup: "Recrutador da área nova: 'Mas você não tem experiência no nosso setor...'",
      memePunchline: "Eu: 'Não tenho experiência NO setor, tenho experiência PRA CARAMBA que serve pro setor.' 💼➡️🎯",
      memeTag: "Tradução de Carreira",
    },
    {
      id: 4,
      quote: "Ninguém muda de área sem passar por um período de 'iniciante de novo'. É temporário, e vale a pena.",
      author: "Recomeço com Propósito",
      tip: "Aceite fazer um curso curto ou certificação básica da área nova — credibilidade rápida vale mais que orgulho.",
      memeTitle: "Ego vs Aprendizado",
      memeSetup: "Meu ego: 'Eu já fui sênior, não vou fazer curso básico.'",
      memePunchline: "Minha conta bancária e meu currículo, em coro: 'Vai, sim.' 💸📚",
      memeTag: "Nível Aprendiz",
    },
    {
      id: 5,
      quote: "Mudar de área não apaga sua história, só adiciona um capítulo novo com o que você já construiu.",
      author: "Reposicionamento de Carreira",
      tip: "Reescreva seu resumo profissional colocando a área nova como foco principal e a antiga como bagagem de apoio.",
      memeTitle: "Apresentação em entrevista",
      memeSetup: "Recrutador: 'Me conta sobre você.'",
      memePunchline: "Eu decidindo, em tempo real, quantos anos da minha vida antiga eu vou mencionar. 🎭⏳",
      memeTag: "Vida Real",
    },
    {
      id: 6,
      quote: "O medo de recomeçar é normal. Ficar onde não faz mais sentido só por medo, é que sai caro depois.",
      author: "Coragem Consciente",
      tip: "Escreva os 3 motivos reais que te fazem querer mudar de área — releia quando a dúvida bater.",
      memeTitle: "Lista de prós e contras",
      memeSetup: "Eu fazendo a lista: 'Vou decidir com toda a racionalidade do mundo.'",
      memePunchline: "A lista: 47 itens, sublinhados, e no fim: 'Ok, meu coração já sabia desde o início.' 💛📝",
      memeTag: "Vida Real",
    },
    {
      id: 7,
      quote: "Sua área antiga te deu disciplina, resiliência ou visão de negócio. Alguma dessas moedas vale ouro em qualquer setor.",
      author: "Bagagem Reaproveitada",
      tip: "Identifique 1 competência transferível (não técnica) que você domina e destaque logo no início do currículo.",
      memeTitle: "Habilidades 'soft' salvando a virada",
      memeSetup: "Recrutador: 'Você não tem experiência técnica na nossa área...'",
      memePunchline: "Eu: 'Não, mas sei lidar com crise, prazo apertado e cliente puto. Serve?' 😤💼",
      memeTag: "Tradução de Carreira",
    },
    {
      id: 8,
      quote: "Trocar de área na metade da carreira exige coragem que ninguém no início de carreira precisa ter.",
      author: "Reconhecimento Justo",
      tip: "Não minimize sua trajetória anterior nas entrevistas — ela é prova de que você já superou uma curva de aprendizado antes.",
      memeTitle: "Comparação com quem começa agora",
      memeSetup: "Colega mais novo(a): 'Nossa, você já trabalhou 10 anos em outra área, deve ser difícil recomeçar.'",
      memePunchline: "Eu: 'Difícil é você não saber que eu já sobrevivi a coisa pior que estagiário questionando prazo.' 😏💪",
      memeTag: "Nível Aprendiz",
    },
    {
      id: 9,
      quote: "Ninguém troca de área por impulso. Se você chegou até aqui pensando nisso, o motivo já é sério o suficiente.",
      author: "Validação da Decisão",
      tip: "Escreva em 3 frases por que a área nova faz mais sentido pra você agora — isso vira sua resposta pronta em entrevistas.",
      memeTitle: "A pergunta que sempre vem",
      memeSetup: "Entrevistador: 'Por que você quer mudar de área depois de tanto tempo na outra?'",
      memePunchline: "Eu, com a resposta ensaiada 47 vezes no espelho, mas ainda gaguejando na hora H. 🪞😅",
      memeTag: "Vida Real",
    },
    {
      id: 10,
      quote: "Área nova, salário inicial menor às vezes é o preço da entrada. Mas é entrada, não destino final.",
      author: "Visão de Longo Prazo",
      tip: "Negocie o que for possível além do salário-base: horário flexível, aprendizado, mentoria — tudo conta no início.",
      memeTitle: "Expectativa salarial na transição",
      memeSetup: "Eu antes: 'Já ganhava X na outra área, é isso que eu quero.'",
      memePunchline: "Eu na proposta real: 'Ok, vamos chamar isso de investimento na minha reinvenção.' 💸🌱",
      memeTag: "Reposicionamento",
    },
    {
      id: 11,
      quote: "Estudar uma área nova depois de adulto(a) é diferente de estudar na faculdade — e isso é uma vantagem, não desvantagem.",
      author: "Maturidade como Ativo",
      tip: "Use sua disciplina de adulto(a) a seu favor: defina um cronograma realista de estudo semanal para a área nova.",
      memeTitle: "Estudando depois dos 30",
      memeSetup: "Colega de curso, 19 anos: 'Vamos virar a noite estudando, é tranquilo.'",
      memePunchline: "Eu, 34 anos: 'Vou estudar até as 22h e dormir feito gente civilizada, valeu.' 😴📚",
      memeTag: "Nível Aprendiz",
    },
    {
      id: 12,
      quote: "A pior transição é a que você não tenta por medo do julgamento alheio. O julgamento passa. O arrependimento, não.",
      author: "Coragem sobre Julgamento",
      tip: "Identifique quem no seu ciclo apoia essa mudança e converse mais com essas pessoas nos próximos dias difíceis.",
      memeTitle: "Reação da família à mudança",
      memeSetup: "Parente no almoço de domingo: 'Mas você não tinha um emprego estável na outra área?'",
      memePunchline: "Eu: 'Tinha, e também tinha vontade de sobreviver emocionalmente até os 60. Prioridades.' 😅🍽️",
      memeTag: "Vida Real",
    },
  ],
  student: [
    {
      id: 1,
      quote: "A educação é o investimento mais seguro para transformar a sua trajetória.",
      author: "Nelson Mandela",
      tip: "Organize seus trabalhos acadêmicos e atividades complementares em um portfólio prático.",
      memeTitle: "Semana de Provas vs Vagas",
      memeSetup: "Professor: 'O trabalho em grupo vale 50% da nota e é para amanhã.'",
      memePunchline: "Eu conciliando aula, prova, trabalho em grupo e mandando currículo: 'Tranquilidade pura!' ☕📚🔥",
      memeTag: "Rotina de Estudante",
    },
    {
      id: 2,
      quote: "Investir em conhecimento gera os frutos mais valiosos para o seu futuro.",
      author: "Benjamin Franklin",
      tip: "Adicione certificações, oficinas e cursos livres no seu resumo profissional.",
      memeTitle: "Vaga de Estágio Exigente",
      memeSetup: "Anúncio da Vaga: 'Procuramos estagiário(a) com 5 anos de experiência e domínio pleno do setor.'",
      memePunchline: "Eu na faculdade: 'Se eu tivesse 5 anos de experiência não era estágio, era a diretoria!' 😅🎓",
      memeTag: "Vida de Universitário",
    },
    {
      id: 3,
      quote: "Nota alta na prova é bom. Portfólio pronto quando a vaga aparecer é o que paga as contas.",
      author: "Foco no Mercado",
      tip: "Transforme um trabalho da faculdade em um case simples de 1 página para mostrar em entrevistas.",
      memeTitle: "Grupo de trabalho da faculdade",
      memeSetup: "Grupo no WhatsApp: '3 pessoas online, 1 apresentação pra amanhã.'",
      memePunchline: "Eu terminando o slide sozinho(a) às 2h: 'Trabalho em equipe é uma jornada solo com créditos coletivos.' 😴📊",
      memeTag: "Rotina de Universitário",
    },
    {
      id: 4,
      quote: "Estágio não é só sobre currículo bonito, é o laboratório onde você testa se a área combina com você de verdade.",
      author: "Experiência Prática",
      tip: "Marque uma conversa de 15 minutos com alguém que já trabalha na sua área e pergunte o que ninguém conta na faculdade.",
      memeTitle: "Teoria vs Prática",
      memeSetup: "Na faculdade: 'O modelo teórico prevê um cenário ideal e controlado.'",
      memePunchline: "No estágio: 'O sistema caiu, o cliente está bravo e o café acabou.' Bem-vindo(a) ao mundo real. ☕🔥",
      memeTag: "Choque de Realidade",
    },
    {
      id: 5,
      quote: "Nota é retrato de uma prova. Currículo é retrato de tudo que você fez além dela. Cuide dos dois.",
      author: "Visão de Futuro",
      tip: "Liste suas atividades extracurriculares (monitoria, intercâmbio, iniciação científica, projetos) e coloque no currículo.",
      memeTitle: "Grade curricular vs vida real",
      memeSetup: "Grade curricular: '40 horas semanais de aula.'",
      memePunchline: "Minha rotina real: aula, estágio, trabalho de conclusão e ainda tentando socializar 15 minutos por semana. 📅😵",
      memeTag: "Rotina de Universitário",
    },
    {
      id: 6,
      quote: "Ninguém sai da faculdade sabendo tudo. Sai sabendo aprender rápido — e isso já é o suficiente pra começar.",
      author: "Confiança na Jornada",
      tip: "Escolha uma ferramenta ou software usado na sua área e faça um tutorial básico ainda esta semana.",
      memeTitle: "Síndrome do impostor formando",
      memeSetup: "Eu, prestes a me formar: 'E se eu não souber nada de verdade?'",
      memePunchline: "Meu histórico escolar, do lado: 'Você passou em tudo, calma.' 📜😅",
      memeTag: "Vida de Universitário",
    },
    {
      id: 7,
      quote: "Faculdade ensina teoria. Estágio ensina prazo, cliente difícil e reunião que podia ser e-mail. Os dois importam.",
      author: "Formação Completa",
      tip: "Se ainda não fez nenhum estágio, candidate-se a 2 vagas de estágio hoje, mesmo que pareçam concorridas.",
      memeTitle: "Primeira reunião de estágio",
      memeSetup: "Meu professor: 'No mercado de trabalho, tudo é dinâmico e colaborativo.'",
      memePunchline: "Minha primeira reunião de estágio: 45 minutos discutindo o nome de um arquivo. 📁😐",
      memeTag: "Choque de Realidade",
    },
    {
      id: 8,
      quote: "Projeto de faculdade também é experiência. Ninguém te disse isso, mas você pode contar do jeito certo.",
      author: "Valorização do que Você Já Fez",
      tip: "Escolha o projeto acadêmico mais completo que você fez e descreva-o como se fosse um case profissional.",
      memeTitle: "TCC virando case de currículo",
      memeSetup: "Eu no currículo: 'Desenvolvi projeto de pesquisa aplicada com metodologia própria.'",
      memePunchline: "A realidade: era o TCC, feito às 3h da manhã, dois dias antes da entrega. 🌙📊",
      memeTag: "Rotina de Universitário",
    },
    {
      id: 9,
      quote: "Você não precisa ter o emprego dos sonhos logo na primeira vaga. Precisa de uma vaga que te ensine algo real.",
      author: "Aprendizado sobre Perfeição",
      tip: "Amplie sua busca para vagas em áreas próximas à sua, não só a ideal — a experiência ali também conta.",
      memeTitle: "Vaga dos sonhos vs vaga disponível",
      memeSetup: "Eu antes de formar: 'Só vou aceitar a vaga perfeita na empresa dos sonhos.'",
      memePunchline: "Eu 6 meses de busca depois: 'Aceito qualquer coisa que tenha crachá e café grátis.' ☕🎫",
      memeTag: "Vida de Universitário",
    },
    {
      id: 10,
      quote: "Universidade também é rede de contatos. Os colegas de hoje são os recrutadores, sócios e referências de amanhã.",
      author: "Networking Silencioso",
      tip: "Participe de 1 evento, palestra ou grupo de estudos da faculdade neste mês, mesmo sem obrigatoriedade.",
      memeTitle: "Grupo de trabalho que virou rede profissional",
      memeSetup: "Eu no grupo de trabalho, reclamando junto dos colegas do prazo apertado.",
      memePunchline: "5 anos depois: um deles me indicou pra vaga que mudou minha carreira. Rede é isso. 🤝📈",
      memeTag: "Rotina de Universitário",
    },
    {
      id: 11,
      quote: "Currículo de universitário não precisa impressionar por experiência, precisa impressionar por potencial demonstrado.",
      author: "Foco no Potencial",
      tip: "Substitua verbos genéricos do currículo ('participei de') por verbos de ação ('organizei', 'liderei', 'criei').",
      memeTitle: "Currículo genérico de universitário",
      memeSetup: "Currículo: 'Participei de trabalhos em grupo e atividades acadêmicas.'",
      memePunchline: "Recrutador lendo isso: 'E quem não participou?' Seja específico(a), sempre. 🧐📄",
      memeTag: "Choque de Realidade",
    },
    {
      id: 12,
      quote: "A ansiedade pré-formatura é real, mas ela mente quando diz que você não está pronto(a) para nada.",
      author: "Confiança Real",
      tip: "Liste 5 habilidades concretas que você desenvolveu na faculdade — a lista sempre é maior do que você imagina.",
      memeTitle: "Últimos meses de faculdade",
      memeSetup: "Eu no último período: 'Será que aprendi alguma coisa mesmo nesses anos todos?'",
      memePunchline: "Meu histórico escolar, meus estágios e meus projetos, em coro: 'Sim. Relaxa.' 📚✅",
      memeTag: "Vida de Universitário",
    },
  ],
  high_school_student: [
    {
      id: 1,
      quote: "O futuro pertence àqueles que se preparam hoje para as oportunidades de amanhã.",
      author: "Foco nos Estudos",
      tip: "Cadastre-se no programa Jovem Aprendiz da sua cidade e mantenha seu boletim escolar atualizado.",
      memeTitle: "ENEM vs Primeiro Emprego",
      memeSetup: "Mãe: 'Já estudou pro ENEM hoje ou tá procurando vaga de Jovem Aprendiz?'",
      memePunchline: "Eu com 15 abas da Wikipedia e 10 candidaturas abertas: 'Estou fazendo os dois ao mesmo tempo!' 🎒🎒✨",
      memeTag: "Ensino Médio",
    },
    {
      id: 2,
      quote: "Sua dedicação diária constrói o caminho para a faculdade e para o mercado de trabalho.",
      author: "Início de Carreira",
      tip: "Destaque suas habilidades em tecnologia, trabalho em equipe e projetos escolares no seu 1º currículo.",
      memeTitle: "Experiência de Ensino Médio",
      memeSetup: "Currículo: 'Campo de Experiência Profissional (Obrigatório)'",
      memePunchline: "Eu: 'Fui líder de grupo na feira de ciências e ajudei na quermesse da escola... conta como gestão de projetos?' 😂💼",
      memeTag: "Primeiros Passos",
    },
    {
      id: 3,
      quote: "Ninguém espera que você já saiba tudo aos 16, 17 anos. Espera-se que você comece.",
      author: "Primeiros Passos",
      tip: "Pesquise 2 cursos técnicos ou faculdades que combinam com o que você curte fazer, mesmo sem certeza total ainda.",
      memeTitle: "Pergunta clássica da família",
      memeSetup: "Tio no almoço: 'E aí, já sabe o que vai fazer da vida?'",
      memePunchline: "Eu, 16 anos: 'Ainda não decidi entre 4 profissões e um surto existencial, tio.' 😅🍽️",
      memeTag: "Clássico de Ensino Médio",
    },
    {
      id: 4,
      quote: "O primeiro currículo não precisa ser perfeito. Precisa existir — e melhorar a cada versão.",
      author: "Primeiros Passos",
      tip: "Escreva hoje seu primeiro rascunho de currículo, mesmo incompleto. Você refina depois, mas precisa começar.",
      memeTitle: "Página em branco do currículo",
      memeSetup: "Documento novo: 'Clique aqui para começar seu currículo.'",
      memePunchline: "Eu, 20 minutos depois, olhando pro cursor piscando: 'Como assim eu preciso resumir minha vida em 1 página?' 😵📄",
      memeTag: "Primeiros Passos",
    },
    {
      id: 5,
      quote: "Escolher uma profissão aos 17 anos não é assinar um contrato vitalício, é só o primeiro passo de muitos.",
      author: "Leveza na Decisão",
      tip: "Converse com 1 pessoa mais velha que já mudou de carreira — ela vai te mostrar que dá pra recomeçar depois também.",
      memeTitle: "Pressão da escolha profissional",
      memeSetup: "Escola: 'Sua escolha de curso vai definir o resto da sua vida.'",
      memePunchline: "Eu, 16 anos, tentando escolher entre 3 áreas enquanto ainda decido o que comer no almoço. 🍽️😰",
      memeTag: "Ensino Médio",
    },
    {
      id: 6,
      quote: "Ser jovem aprendiz não é 'só' nada. É a primeira prova real de que você consegue equilibrar estudo e trabalho.",
      author: "Valorização do Início",
      tip: "Pesquise hoje 2 programas de Jovem Aprendiz próximos de você e veja os requisitos de cada um.",
      memeTitle: "Primeiro contracheque de aprendiz",
      memeSetup: "Eu recebendo o primeiro salário de aprendiz: 'Vou guardar tudo, virar investidor.'",
      memePunchline: "Eu 2 dias depois, no shopping: 'Foi mal, futuro eu.' 🛍️😅",
      memeTag: "Ensino Médio",
    },
    {
      id: 7,
      quote: "Escolher um curso técnico ou uma faculdade não é a única decisão da sua vida. É só a próxima.",
      author: "Leveza sobre o Futuro",
      tip: "Faça um teste vocacional simples online hoje — não pra decidir tudo, só pra ganhar mais clareza.",
      memeTitle: "Pressão da escolha do vestibular",
      memeSetup: "Todo mundo ao redor: 'Já decidiu o que vai fazer depois do ensino médio?'",
      memePunchline: "Eu, 17 anos, mudando de ideia pela quinta vez este mês só essa semana. 🔄🎒",
      memeTag: "Ensino Médio",
    },
    {
      id: 8,
      quote: "Trabalhar cedo (Jovem Aprendiz, estágio) não rouba sua infância, te dá uma vantagem que muita gente só ganha depois.",
      author: "Vantagem do Início Cedo",
      tip: "Se ainda não trabalha, pesquise hoje se sua escola tem parceria com programas de Jovem Aprendiz.",
      memeTitle: "Colegas reagindo ao primeiro emprego",
      memeSetup: "Colega de classe: 'Nossa, você já trabalha? Não prefere aproveitar mais essa fase?'",
      memePunchline: "Eu, com crachá e experiência real: 'Prefiro aproveitar com dinheiro no bolso, obrigado(a).' 💳😎",
      memeTag: "Primeiros Passos",
    },
    {
      id: 9,
      quote: "Boletim bom importa, mas o que você faz com o tempo livre também conta uma história sobre você.",
      author: "Além da Nota",
      tip: "Liste hobbies ou atividades extracurriculares que mostram habilidades como organização, criatividade ou liderança.",
      memeTitle: "Currículo do primeiro emprego",
      memeSetup: "Formulário de vaga: 'Descreva suas experiências e habilidades relevantes.'",
      memePunchline: "Eu, 16 anos: 'Sou monitor(a) de matemática e organizo o grupo de estudo. Isso conta?' Conta, sim! 📐✅",
      memeTag: "Primeiros Passos",
    },
    {
      id: 10,
      quote: "Ansiedade sobre o futuro é normal aos 16, 17 anos. Ninguém espera que você já tenha tudo resolvido.",
      author: "Acolhimento da Incerteza",
      tip: "Converse com o orientador educacional da sua escola, mesmo que só para organizar as ideias.",
      memeTitle: "Crise existencial adolescente",
      memeSetup: "Eu às 23h: 'E se eu escolher a profissão errada e estragar minha vida toda?'",
      memePunchline: "Eu no dia seguinte, focado(a) em passar de ano: crise adiada com sucesso. 😅📖",
      memeTag: "Ensino Médio",
    },
    {
      id: 11,
      quote: "Sua primeira entrevista de emprego não precisa ser perfeita. Precisa ser a primeira de muitas.",
      author: "Primeira Vez Não Define Tudo",
      tip: "Pratique respostas simples para 'fale sobre você' e 'por que quer essa vaga' antes da sua primeira entrevista.",
      memeTitle: "Primeira entrevista de Jovem Aprendiz",
      memeSetup: "Recrutador: 'Me conta um pouco sobre suas experiências.'",
      memePunchline: "Eu, 16 anos: 'Bem, eu ajudei minha mãe na feira e sou muito responsável com meu celular.' 😅📱",
      memeTag: "Primeiros Passos",
    },
    {
      id: 12,
      quote: "Todo profissional admirado hoje também teve 16 anos sem saber o que fazer da vida. Isso passa.",
      author: "Perspectiva de Tempo",
      tip: "Pesquise a trajetória de alguém que você admira profissionalmente — quase sempre o caminho não foi reto.",
      memeTitle: "Trajetória perfeita nas redes",
      memeSetup: "Perfil de sucesso na internet: 'Sempre soube o que queria ser.'",
      memePunchline: "A biografia real dessa pessoa: trocou de curso 3 vezes e só decidiu aos 24 anos. 📚🔄",
      memeTag: "Ensino Médio",
    },
  ],
  first_job: [
    {
      id: 1,
      quote: "Todo profissional renomado começou com a primeira oportunidade e muita vontade de aprender.",
      author: "Desenvolvimento Pessoal",
      tip: "Destaque experiências de liderança na escola/faculdade, trabalhos voluntários ou projetos de equipe.",
      memeTitle: "O dilema do 1º emprego",
      memeSetup: "Vaga Inicial: 'Pré-requisito: Experiência anterior demonstrada.'",
      memePunchline: "Eu querendo o 1º emprego pra ter experiência, mas precisando de experiência pra ter o 1º emprego: 🔄🤯",
      memeTag: "Primeiros Passos",
    },
    {
      id: 2,
      quote: "Ninguém nasce sabendo. Todo mundo que você admira também mandou o primeiro currículo com o coração na mão.",
      author: "Início de Carreira",
      tip: "Liste 3 projetos pessoais, acadêmicos ou voluntários que mostrem na prática o que você sabe fazer.",
      memeTitle: "Entrevista de estágio",
      memeSetup: "Recrutador: 'Fale sobre um desafio profissional que você superou.'",
      memePunchline: "Eu, 19 anos: 'Bem, uma vez o Wi-Fi caiu durante minha apresentação de TCC e eu improvisei.' 😅",
      memeTag: "Primeiro Emprego",
    },
    {
      id: 3,
      quote: "A primeira oportunidade não define seu teto, só abre a porta. O resto você constrói.",
      author: "Foco no Futuro",
      tip: "Peça uma indicação ou recomendação para um professor, chefe de estágio ou líder de projeto.",
      memeTitle: "Salário de estagiário vs Expectativa",
      memeSetup: "Eu antes de assinar: 'Vou economizar, viajar, comprar um carro...'",
      memePunchline: "Eu depois do primeiro contracheque: 'Ok, vou economizar o vale-transporte.' 🚌💸",
      memeTag: "Realidade do Estágio",
    },
    {
      id: 4,
      quote: "Você não precisa ser o(a) melhor candidato(a) do processo. Precisa ser o(a) mais preparado(a) que apareceu naquele dia.",
      author: "Foco no Presente",
      tip: "Simule hoje 3 perguntas comuns de entrevista em voz alta, sozinho(a) ou com alguém de confiança.",
      memeTitle: "Treino de entrevista",
      memeSetup: "Eu treinando na frente do espelho: 'Meu maior defeito é ser perfeccionista.'",
      memePunchline: "Eu na entrevista de verdade: gaguejando o próprio nome. 🪞😅",
      memeTag: "Primeiro Emprego",
    },
    {
      id: 5,
      quote: "Todo mundo que hoje parece confiante numa entrevista já gaguejou muito na primeira também.",
      author: "Confiança em Construção",
      tip: "Grave-se respondendo 'fale sobre você' e assista de volta — parece estranho, mas funciona.",
      memeTitle: "Roteiro decorado vs entrevista real",
      memeSetup: "Eu decorando minha apresentação de 2 minutos na noite anterior.",
      memePunchline: "Na entrevista: 'Bem, meu nome é... eu... trabalho... currículo... obrigado(a).' 🎤😵",
      memeTag: "Primeiros Passos",
    },
    {
      id: 6,
      quote: "Seu primeiro salário não vai resolver sua vida financeira, mas vai te ensinar mais sobre ela do que qualquer curso.",
      author: "Aprendizado na Prática",
      tip: "Antes de gastar o primeiro contracheque, separe pelo menos 10% e veja como isso se sente.",
      memeTitle: "Planejamento financeiro do primeiro salário",
      memeSetup: "Eu antes de receber: 'Vou fazer uma planilha, dividir por categoria, ser disciplinado(a).'",
      memePunchline: "Eu no dia do pagamento: comprando algo 'só para comemorar' antes mesmo de abrir a planilha. 🎉📉",
      memeTag: "Realidade do Estágio",
    },
    {
      id: 7,
      quote: "Ninguém te contrata só pelo diploma. Te contratam pelo que você demonstra saber fazer com ele.",
      author: "Prova pela Prática",
      tip: "Monte um mini-portfólio, mesmo simples, com 2-3 exemplos do que você já produziu — projeto, código, texto, planilha.",
      memeTitle: "Diploma vs Portfólio",
      memeSetup: "Eu no currículo: 'Formado(a) em [área], pronto(a) para o mercado.'",
      memePunchline: "Recrutador: 'Legal, mas você tem algo pra eu ver funcionando?' Eu: '...deixa eu criar isso rapidinho.' 😅💻",
      memeTag: "Primeiro Emprego",
    },
    {
      id: 8,
      quote: "Seu primeiro chefe não vai definir o resto da sua carreira. Vai só te ensinar o que evitar ou repetir depois.",
      author: "Aprendizado com Qualquer Experiência",
      tip: "Mesmo num primeiro emprego difícil, anote 1 lição prática que valha a pena levar para o próximo.",
      memeTitle: "Primeiro chefe icônico",
      memeSetup: "Meu primeiro chefe: 'Aqui somos uma família.'",
      memePunchline: "Também meu primeiro chefe: me chamando às 22h de domingo por uma 'urgência'. 📵😑",
      memeTag: "Realidade do Estágio",
    },
    {
      id: 9,
      quote: "Não ter experiência formal não significa não ter competência. Você só ainda não teve a chance de provar.",
      author: "Potencial Não Reconhecido",
      tip: "Transforme experiências informais (freelance, ajuda a familiares, projetos pessoais) em linhas de currículo válidas.",
      memeTitle: "Experiência 'informal' que conta",
      memeSetup: "Eu pensando que não tenho experiência nenhuma.",
      memePunchline: "Minha memória, 5 minutos depois: 'E aquela vez que você organizou o evento da faculdade sozinho(a)?' 🎉📋",
      memeTag: "Primeiros Passos",
    },
    {
      id: 10,
      quote: "A primeira vaga não precisa ser a ideal. Precisa ser a porta que te coloca dentro do mercado.",
      author: "Entrada Estratégica",
      tip: "Amplie o raio de busca: considere empresas menores ou vagas híbridas que ainda te dão a experiência que falta.",
      memeTitle: "Primeira vaga aceita com ressalvas",
      memeSetup: "Eu aceitando a vaga: 'Não é exatamente o que sonhei, mas é um começo.'",
      memePunchline: "Eu 1 ano depois, já promovido(a): 'Melhor decisão que tomei, e olha que reclamei bastante.' 😅📈",
      memeTag: "Foco no Futuro",
    },
    {
      id: 11,
      quote: "Cada 'não' no início de carreira dói mais porque você ainda não tem repertório de 'sins' para comparar. Isso muda rápido.",
      author: "Primeiros Nãos",
      tip: "Guarde os feedbacks que receber, mesmo os de reprovação — em poucos meses eles vão parecer bem menores.",
      memeTitle: "Primeira rejeição de emprego",
      memeSetup: "E-mail: 'Infelizmente seguiremos com outro candidato.'",
      memePunchline: "Eu, entrando em modo drama por 20 minutos e depois aplicando pra próxima vaga. Assim que se faz. 😭➡️😤",
      memeTag: "Primeiro Emprego",
    },
    {
      id: 12,
      quote: "Você não precisa saber fazer tudo no primeiro emprego. Precisa estar disposto(a) a aprender rápido o que não sabe.",
      author: "Vontade sobre Perfeição",
      tip: "Numa entrevista, é melhor admitir uma lacuna e mostrar disposição de aprender do que fingir domínio total.",
      memeTitle: "Pergunta sobre habilidade que você não tem",
      memeSetup: "Entrevistador: 'Você tem experiência com essa ferramenta específica?'",
      memePunchline: "Eu: 'Ainda não, mas aprendo rápido — e já pesquisei sobre ela ontem à noite, olha só.' 🔍😅",
      memeTag: "Foco no Presente",
    },
  ],
  freelance: [
    {
      id: 1,
      quote: "Construir seu próprio caminho exige autonomia, mas traz o poder de moldar seus próprios resultados.",
      author: "Mentalidade Autônoma",
      tip: "Apresente suas soluções focando no problema real do cliente e mostre depoimentos de quem já atendeu.",
      memeTitle: "O 'ajustezinho' rápido",
      memeSetup: "Cliente: 'É só um ajustezinho de 5 minutos, rapidinho você faz!'",
      memePunchline: "O ajustezinho: Refazer o serviço inteiro do zero em um final de semana. 📉🫣",
      memeTag: "Vida de Autônomo",
    },
    {
      id: 2,
      quote: "Quem trabalha por conta própria não tem chefe, tem vários — e todos acham que o prazo é 'pra ontem'.",
      author: "Humor Autônomo",
      tip: "Formalize um orçamento por escrito antes de começar qualquer projeto novo, mesmo com clientes antigos.",
      memeTitle: "Orçamento vs Escopo real",
      memeSetup: "Cliente: 'Fechado! Só isso mesmo que combinamos.'",
      memePunchline: "Uma semana depois: 'Ah, e será que dá pra incluir só mais uma telinha?' 🙃",
      memeTag: "Escopo Fantasma",
    },
    {
      id: 3,
      quote: "Cada 'não' de um cliente te aproxima do cliente certo, que valoriza o que você entrega.",
      author: "Resiliência Autônoma",
      tip: "Divulgue um resultado recente do seu trabalho nas redes — prova social vende mais que autoelogio.",
      memeTitle: "Fatura enviada",
      memeSetup: "Eu enviando a fatura: 'Só um lembrete gentil sobre o pagamento combinado 😊'",
      memePunchline: "Eu 5 dias depois, no terceiro 'oi, tudo bem?': 'Só um lembrete GENTIL.' 🫠",
      memeTag: "Vida de Autônomo",
    },
    {
      id: 4,
      quote: "Autonomia é liberdade de escolher os problemas que você resolve — e o preço que cobra por resolvê-los.",
      author: "Mentalidade Autônoma",
      tip: "Revise seus preços hoje: cobrar barato demais não atrai cliente bom, atrai cliente que negocia até o fim.",
      memeTitle: "Desconto pedido no PIX",
      memeSetup: "Cliente: 'Consegue um descontinho se eu pagar no PIX à vista?'",
      memePunchline: "Eu, cobrando o mesmo valor de qualquer forma: 'Consigo, sim: o desconto de eu não desistir de você.' 😅💳",
      memeTag: "Escopo Fantasma",
    },
    {
      id: 5,
      quote: "Cliente bom não é o que paga mais rápido, é o que respeita seu tempo e seu escopo combinado.",
      author: "Seleção de Clientes",
      tip: "Antes de aceitar o próximo projeto, avalie se o cliente respeitou prazos e comunicação no primeiro contato.",
      memeTitle: "Red flag na primeira mensagem",
      memeSetup: "Cliente no primeiro contato: 'É rapidinho, acho que dá pra fazer hoje ainda, né?'",
      memePunchline: "Eu, com 10 anos de experiência em decifrar red flags: 'Vou cobrar urgência. Em dobro.' 🚩💰",
      memeTag: "Vida de Autônomo",
    },
    {
      id: 6,
      quote: "Diversificar clientes não é desconfiança, é sobrevivência. Depender de um só é apostar sua renda numa cadeira só.",
      author: "Segurança Financeira",
      tip: "Reserve 30 minutos esta semana para prospectar 1 cliente novo, mesmo estando com a agenda cheia agora.",
      memeTitle: "Cliente único sumindo",
      memeSetup: "Meu único grande cliente: 'Vamos pausar o projeto por uns tempos.'",
      memePunchline: "Eu, sem plano B: revisando currículo enquanto finjo calma total. 😅📄",
      memeTag: "Escopo Fantasma",
    },
    {
      id: 7,
      quote: "Contrato por escrito não é falta de confiança no cliente, é respeito pelo seu próprio tempo e trabalho.",
      author: "Profissionalismo Autônomo",
      tip: "Crie um modelo simples de contrato ou termo de escopo e use em todo projeto novo, mesmo pequeno.",
      memeTitle: "Projeto sem contrato",
      memeSetup: "Eu aceitando o projeto 'na confiança, combinado no WhatsApp mesmo'.",
      memePunchline: "3 semanas depois: 'Mas eu não falei isso' virou o assunto principal da conversa. 📝😩",
      memeTag: "Escopo Fantasma",
    },
    {
      id: 8,
      quote: "Cliente que só reclama de preço e nunca do resultado, geralmente não valoriza o resultado — só quer pagar pouco.",
      author: "Leitura de Cliente",
      tip: "Ao invés de baixar preço na negociação, ofereça reduzir escopo. Isso filtra quem valoriza seu trabalho de verdade.",
      memeTitle: "Negociação de preço",
      memeSetup: "Cliente: 'Consegue fazer mais barato? Sei que tem gente que cobra menos.'",
      memePunchline: "Eu: 'Tem, sim. E o resultado costuma custar caro depois, de outro jeito.' 💬💸",
      memeTag: "Vida de Autônomo",
    },
    {
      id: 9,
      quote: "Trabalhar sozinho(a) não significa trabalhar sem rede. Outros freelancers são aliados, não concorrentes o tempo todo.",
      author: "Comunidade Autônoma",
      tip: "Entre em 1 grupo ou comunidade de profissionais da sua área para trocar indicações e experiências.",
      memeTitle: "Freelancer isolado(a)",
      memeSetup: "Eu trabalhando sozinho(a) há meses, achando que essa é a única forma de ser autônomo(a).",
      memePunchline: "Eu descobrindo uma comunidade de freelancers: 'Espera, vocês trocam indicação de cliente? Onde estava isso?' 🤝😲",
      memeTag: "Vida de Autônomo",
    },
    {
      id: 10,
      quote: "Cobrar pelo valor que você entrega, não só pelas horas trabalhadas, é o que separa freelancer de empresa de verdade.",
      author: "Precificação por Valor",
      tip: "Para o próximo orçamento, calcule também o resultado que o cliente ganha com seu trabalho, não só suas horas.",
      memeTitle: "Precificação por hora vs por valor",
      memeSetup: "Eu calculando: '3 horas de trabalho, vou cobrar X.'",
      memePunchline: "Eu esquecendo de contar os 10 anos de experiência que me fizeram resolver isso em 3 horas e não em 3 dias. ⏱️💡",
      memeTag: "Escopo Fantasma",
    },
    {
      id: 11,
      quote: "Momento de vazio na agenda dói, mas também é o único tempo que você tem pra investir em prospecção e portfólio.",
      author: "Aproveitar a Pausa",
      tip: "Use um dia sem demanda de cliente para atualizar seu portfólio ou pedir depoimentos de projetos antigos.",
      memeTitle: "Semana sem projeto novo",
      memeSetup: "Eu numa semana sem demanda: 'Vou aproveitar pra organizar tudo, estudar, prospectar.'",
      memePunchline: "Eu, na prática: maratona de série e uma culpa profunda por não ter feito nada disso. 📺😅",
      memeTag: "Vida de Autônomo",
    },
    {
      id: 12,
      quote: "Autônomo bem-sucedido não é quem nunca teve mês ruim, é quem aprendeu a atravessar os meses ruins sem desistir.",
      author: "Resiliência Financeira",
      tip: "Se possível, guarde parte da renda dos meses bons para amortecer os meses de agenda mais vazia.",
      memeTitle: "Mês bom vs mês ruim",
      memeSetup: "Mês bom: 4 clientes, agenda cheia, 'finalmente estabilizei'.",
      memePunchline: "Mês seguinte: 0 clientes novos e eu reaprendendo a rezar pro telefone tocar. 📵🙏",
      memeTag: "Vida de Autônomo",
    },
  ],
};

interface AreaMemeVariant {
  tip: string;
  memeTitle: string;
  memeSetup: string;
  memePunchline: string;
  memeTag: string;
}

function genericAreaVariants(area: string): AreaMemeVariant[] {
  return [
    {
      tip: `Separe 15 minutos hoje para praticar uma habilidade de ${area} e registre o que aprendeu no seu portfólio.`,
      memeTitle: `Quando você escolhe ${area}`,
      memeSetup: "Pessoa: 'Vou só pesquisar um pouco sobre a área.'",
      memePunchline: `Duas horas depois: 14 abas abertas, um curso salvo e vontade de começar um projeto de ${area}.`,
      memeTag: "Vida na Área",
    },
    {
      tip: `Peça 15 minutos de conversa com alguém que já atua em ${area} — pergunta real vale mais que pesquisa genérica.`,
      memeTitle: `O plano de estudos de ${area}`,
      memeSetup: "Eu no domingo: 'Essa semana vou estudar 1 hora por dia, sem falta.'",
      memePunchline: "Eu na quinta-feira: recuperando as 4 horas perdidas num único sábado de pânico.",
      memeTag: "Vida na Área",
    },
    {
      tip: `Escreva 3 motivos concretos que te levaram a ${area} — isso vira resposta pronta pra entrevista.`,
      memeTitle: `Explicando ${area} pra família`,
      memeSetup: "Parente no almoço: 'Mas o que exatamente você faz?'",
      memePunchline: "Eu, na quinta tentativa de explicação, desistindo e dizendo 'trabalho com computador'.",
      memeTag: "Vida na Área",
    },
  ];
}

const AREA_MEME_CATALOG: { pattern: RegExp; variants: AreaMemeVariant[] }[] = [
  {
    pattern: /(tecnologia|program|dados|software|dev|ti)/,
    variants: [
      {
        tip: "Escolha um pequeno problema da área e transforme-o em um projeto prático. Portfólio vence promessa.",
        memeTitle: "Só mais um tutorial",
        memeSetup: "Eu: 'Depois deste tutorial eu começo o projeto.'",
        memePunchline: "O tutorial: parte 47 de 48. O projeto: ainda na pasta Downloads.",
        memeTag: "Rotina Tech",
      },
      {
        tip: "Revise um trecho de código antigo seu e reescreva com o que você aprendeu desde então.",
        memeTitle: "Código de 6 meses atrás",
        memeSetup: "Eu abrindo um projeto antigo: 'Quem escreveu essa aberração?'",
        memePunchline: "O git blame: era eu, sexta-feira à noite, prazo em cima.",
        memeTag: "Rotina Tech",
      },
      {
        tip: "Mande uma mensagem hoje perguntando sobre uma vaga técnica júnior — não espere se sentir 100% pronto(a).",
        memeTitle: "Requisito da vaga júnior",
        memeSetup: "Anúncio: 'Vaga júnior, requer 3 anos de experiência com a ferramenta lançada há 2 anos.'",
        memePunchline: "Eu, calculando se isso é matematicamente possível.",
        memeTag: "Rotina Tech",
      },
    ],
  },
  {
    pattern: /(direito|jurid|administr|negoc|financ|contab)/,
    variants: [
      {
        tip: "Leia um caso real da área, resuma o problema em cinco linhas e explique qual seria sua decisão.",
        memeTitle: "O documento era simples",
        memeSetup: "Alguém: 'É só dar uma olhadinha rápida neste documento.'",
        memePunchline: "O documento: 37 páginas, 12 anexos e uma reunião marcada para ontem.",
        memeTag: "Vida Corporativa",
      },
      {
        tip: "Organize 1 planilha ou processo que você já domina e transforme em exemplo prático pro currículo.",
        memeTitle: "Reunião de alinhamento",
        memeSetup: "Convite: 'Reunião rápida, 15 minutos, pra alinhar um ponto.'",
        memePunchline: "1 hora e 40 depois: ainda alinhando o mesmo ponto.",
        memeTag: "Vida Corporativa",
      },
      {
        tip: "Pratique explicar um termo técnico da área em uma frase simples — isso impressiona em entrevista.",
        memeTitle: "Prazo do relatório",
        memeSetup: "Chefe: 'Preciso disso pra ontem, mas com calma, sem pressão.'",
        memePunchline: "Eu, decodificando: isso é urgente ou não é?",
        memeTag: "Vida Corporativa",
      },
    ],
  },
  {
    pattern: /(saude|medicina|enferm|psico|fisi|odonto)/,
    variants: [
      {
        tip: "Revise um conceito essencial da área e transforme-o em uma explicação simples, como se estivesse ensinando alguém.",
        memeTitle: "Plantão do conhecimento",
        memeSetup: "Eu: 'Hoje vou estudar só um tópico.'",
        memePunchline: "O tópico: tem 18 capítulos, 4 protocolos e uma prova surpresa.",
        memeTag: "Rotina da Saúde",
      },
      {
        tip: "Anote 1 atendimento ou caso de estudo que te ensinou algo novo essa semana.",
        memeTitle: "Escala de plantão",
        memeSetup: "Escala publicada: 'Só mais um plantão de 12 horas, tranquilo.'",
        memePunchline: "Hora 13: ainda lá, resolvendo 'só mais uma coisinha'.",
        memeTag: "Rotina da Saúde",
      },
      {
        tip: "Pratique hoje uma resposta curta pra 'por que você escolheu essa área' — quase sempre perguntam.",
        memeTitle: "Pergunta clássica da área da saúde",
        memeSetup: "Alguém no elevador: 'Posso te perguntar uma coisa rapidinho?'",
        memePunchline: "Eu, sabendo que 'rapidinho' nessa área nunca é rápido.",
        memeTag: "Rotina da Saúde",
      },
    ],
  },
  {
    pattern: /(marketing|comunic|design|criativ|audiovisual)/,
    variants: [
      {
        tip: "Analise uma campanha ou peça da área que você viu hoje e anote o que funcionou — e o que você faria diferente.",
        memeTitle: "Briefing do cliente",
        memeSetup: "Cliente: 'Quero algo simples, mas impactante, moderno e diferente.'",
        memePunchline: "Eu: 'Perfeito. Só preciso de mais 12 referências e três cafés.'",
        memeTag: "Briefing Real",
      },
      {
        tip: "Monte 1 peça simples hoje pro seu portfólio, mesmo sem cliente real — projeto autoral também conta.",
        memeTitle: "Rodada de feedback",
        memeSetup: "Cliente: 'Só um ajuste pequeno: pode deixar mais pra direita? Ou esquerda. Vê o que fica melhor.'",
        memePunchline: "Versão 14 do arquivo, idêntica à versão 2.",
        memeTag: "Briefing Real",
      },
      {
        tip: "Escreva o resultado (não só a tarefa) de um projeto recente — números e impacto pesam mais que descrição.",
        memeTitle: "Prazo criativo",
        memeSetup: "Combinado: 'Entrega sexta, sem pressa, capricha.'",
        memePunchline: "Quinta à noite: capricho e pressa dividindo o mesmo espaço na minha cabeça.",
        memeTag: "Briefing Real",
      },
    ],
  },
];

function personalizeMotivation(
  motivation: DailyMotivation,
  profile: DailyMotivationProfile | undefined,
  variantIndex: number
): DailyMotivation {
  const area = profile?.area?.trim() || profile?.studyCourse?.trim();
  if (!area) return motivation;

  const normalized = area.normalize("NFD").replace(/[̀-ͯ]/g, "").toLowerCase();
  const currentArea = profile?.currentArea?.trim();
  const isTransition = profile?.careerSegment === "career_change" && currentArea;
  const areaLabel = isTransition ? `${currentArea} → ${area}` : area;

  const matched = AREA_MEME_CATALOG.find((entry) => entry.pattern.test(normalized));
  const variants = matched ? matched.variants : genericAreaVariants(area);
  const { tip, memeTitle, memeSetup, memePunchline, memeTag } = variants[variantIndex % variants.length];

  return {
    ...motivation,
    tip: isTransition
      ? `Na transição ${areaLabel}, escolha uma habilidade transferível da sua experiência anterior e mostre como ela gera valor na nova área.`
      : tip,
    memeTitle: isTransition ? `Transição: ${areaLabel}` : memeTitle,
    memeSetup,
    memePunchline,
    memeTag: isTransition ? "Mudança de Carreira" : memeTag,
  };
}

const LOW_MOOD_TIP =
  "Hoje pode ser só sobre continuar de pé. Escolha uma única ação pequena — nem precisa ser sobre carreira — e conte isso como vitória do dia.";

export function getDailyMotivation(
  status?: string | null,
  profile?: DailyMotivationProfile,
  mood?: string | null
): DailyMotivation {
  const validStatus: EmploymentStatusKey =
    status && status in MOTIVATION_CATALOG
      ? (status as EmploymentStatusKey)
      : "unemployed_active";

  const catalog = MOTIVATION_CATALOG[validStatus] || MOTIVATION_CATALOG.unemployed_active;

  // Seed determinístico por dia do ano (ex: 2026-07-24)
  const today = new Date();
  const dayOfYear = Math.floor(
    (today.getTime() - new Date(today.getFullYear(), 0, 0).getTime()) / (1000 * 60 * 60 * 24)
  );

  const index = dayOfYear % catalog.length;
  const personalized = personalizeMotivation(catalog[index], profile, dayOfYear);

  if (mood === "low" || mood === "rough") {
    return { ...personalized, tip: LOW_MOOD_TIP };
  }
  return personalized;
}
